### ISSUE TITLE
Consider publishing cachefs separately

### ISSUE THREAD

**Issue by tmc** [ancientlore/whisper#5]
I'm interested in using cachefs but would prefer to take on a minimal set of additional dependencies -- could you please consider having cachefs be it's own module?

**Comment by ancientlore** [comment]
@tmc that is a good idea. I have moved it to github.com/ancientlore/cachefs.

I'm updating this code to reference it and maintain compatibility, in case anyone is references it here.

**Comment by tmc** [comment]
Thanks for the fast turn-around! much appreciated.
